title: Marcus Mu's Corner
description: Marcus Mu's little personal corner in the vast cyberspace
url: "http://chunkhang.com"

permalink: pretty

collections:
  posts:
    permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - serve
  - deploy
