title: Marcus Mu
description: >
  Hello World.
  I am Marcus Mu, a tea-loving programmer with diverse interests.
url: "http://chunkhang.com"
logo: /assets/seo-logo.png

plugins:
  - jekyll-paginate-v2
  - jekyll-assets
  - jekyll-feed

permalink: pretty

collections:
  posts:
    permalink: "/blog/:title/"
  category:
    output: true

pagination:
  enabled: true
  sort_reverse: true
  permalink: "/:num/"
  title: ":title - Page :num"
  per_page: 5
  trail:
    before: 2
    after: 2

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

assets:
  raw_precompile:
    - seo-img.jpg
    - seo-logo.png

defaults:
  - scope:
      path: ""
    values:
      image: /assets/seo-img.jpg

exclude:
  - Gemfile
  - Gemfile.lock
  - serve
  - deploy
  - favicon.sketch
