title: Marcus Mu
description: My little personal corner in the vast cyberspace
url: "http://chunkhang.com"

plugins:
  - jekyll-paginate-v2

permalink: pretty

collections:
  posts:
    permalink: "/blog/:title/"

pagination:
  enabled: true
  sort_reverse: true
  permalink: "/:num/"
  title: ":title - Page :num"
  per_page: 5
  trail:
    before: 2
    after: 2

assets:
  gzip: true
  compress:
    js: uglifier

exclude:
  - Gemfile
  - Gemfile.lock
  - serve
  - deploy
  - favicon.sketch
