#!/bin/zsh

if [ "$#" -ne 3 ]; then
    echo "usage: pdf <html input path> <scss input path> <pdf output path>"
else
    # Make a copy of html file
    HTML_PATH=$(dirname $1)'/copy-'$(basename $1)
    cp $1 $HTML_PATH
    # Use relative path for assets
    sed -i '' 's/"\/assets/"..\/assets/g' $HTML_PATH
    # Preprocess custom scss file
    CSS_PATH=$(dirname $2)'/'$(basename -s .scss $2)'.css'
    bundle exec sass --no-cache --sourcemap=none $2 $CSS_PATH
    # Convert html to pdf
    bundle exec wkhtmltopdf --print-media-type --disable-javascript --disable-smart-shrinking --page-size A4 --margin-left 0 --margin-right 0 --margin-top 0 --margin-bottom 0 --user-style-sheet $CSS_PATH $HTML_PATH $3
    # Clean up
    rm $HTML_PATH $CSS_PATH $2
fi

